### ISSUE TITLE
Change front page text

### ISSUE THREAD

**Issue by johanrung** [ScilifelabDataCentre/covid-portal#59]
Remove this text on middle of front page :

> ## _Under construction_
> Welcome to the Swedish COVID-19 Data Portal. Here you can find lots of useful information.
>
> > För information på svenska, klicka här

and correspondingly on Swedish site.

This conforms with the appearance of https://covid19dataportal.org.

**Comment by ewels** [comment]
The EBI site has an _About this portal_ section on the front page:

> **About this portal**
> The COVID-19 Data Portal was launched in April 2020 to bring together relevant datasets for sharing and analysis in an effort to accelerate coronavirus research. It enables researchers to upload, access and analyse COVID-19 related reference data and specialist datasets as part of the wider European COVID-19 Data Platform.

I was planning for the _"Under construction"_ text to mimic this. I think that we need some kind of introduction text to explain the purpose of the site for people when they first arrive.

I also quite like having the _För information på svenska, klicka här_ text as it's not immediately obvious that there is a multilingual option otherwise (the fairly innocuous flags are obvious if you know that they should be there, but not the first thing you see otherwise). Happy to make this a little prettier instead of deleting it, this was just holding content until a proper introduction was written.

Phil

**Comment by johanrung** [comment]
Yes...  you have a point. What about writing "The Swedish COVID-19 Data Portal provides information, guidelines, tools and services, in particular to support researchers in Sweden to utilise national and European infrastructures for data sharing. It is closely aligned with the European COVID-19 Data Platform hosted at EMBL-EBI and launched in April 2020."

In Swedish: "Den svenska dataportalen för COVID-19 tillhandahåller information, riktlinjer, verktyg och tjänster, särskilt för att stödja forskare i Sverige att använda nationell och europeisk infrastruktur för datadelning. Portalen samordnas med den europeiska dataportalen för COVID-19 vid EMBL-EBI som är i drift sedan april 2020."

Then we can keep "För information på svenska, klicka här", and keep the same texts under the "About the site" links.

**Comment by talavis** [comment]
The English wording to me implies that our portal launced in April 2020. Maybe "It is closely aligned with the European COVID-19 Data Platform hosted at EMBL-EBI, launched in April 2020." as the last sentence?

**Comment by talavis** [comment]
How do we want the about page updated? Currently it is:
```
---

The Swedish COVID-19 Data Portal is written and managed by the SciLifeLab Data Centre and partners.

---

To be written:

* About Swedish plan
* Updated hub plan
* EC action plan
* EBI data portal plan
```
Do we want to remove it and replace it with the new text, or keep the info about us making it?

**Comment by johanrung** [comment]
Yes, keep the info about us making it please.
